version: "3.11"
services:
  db:
    image: uselagoon/postgres-15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    environment:
      - PROD=1
    env_file:
      - .prod.env

  app:
    build:
      context: .
    env_file:
      - .prod.env
    container_name: fastapi_app
    ports:
      - 8888:8000
    depends_on:
      - db
