version: "3.11"
services:
  db:
    image: uselagoon/postgres-15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: employees_app
    ports:
      - 8888:8000
    depends_on:
      - db
