"""New

Revision ID: 78dd55e9ca17
Revises: ccbcd1a27af6
Create Date: 2023-06-11 12:36:07.892525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dd55e9ca17'
down_revision = 'ccbcd1a27af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
